/* =============================================
   specialites.js — Source unique des spécialités Bac Pro
   Utilisé par app.js et grille_items.html
   Ne pas dupliquer dans les autres fichiers.
============================================= */

const SPECIALITES_BAC_PRO = [
  {nom:"Accompagnement soins et services à la personne",grpM:"C",grpPC:"5"},
  {nom:"Animation - enfance et personnes âgées",grpM:"C",grpPC:""},
  {nom:"Aéronautique option Avionique",grpM:"B",grpPC:"1"},
  {nom:"Aéronautique option Structure",grpM:"B",grpPC:"1"},
  {nom:"Aéronautique option Systèmes",grpM:"B",grpPC:"1"},
  {nom:"Aménagement et finition du bâtiment",grpM:"B",grpPC:"3"},
  {nom:"Artisanat et métiers d'art option Communication visuelle pluri média",grpM:"B",grpPC:"4"},
  {nom:"Artisanat et métiers d'art option Marchandisage visuel",grpM:"B",grpPC:"6"},
  {nom:"Artisanat et métiers d'art option Métiers de l'enseigne et de la signalétique",grpM:"B",grpPC:"6"},
  {nom:"Artisanat et métiers d'art option Tapissier d'ameublement",grpM:"B",grpPC:"6"},
  {nom:"Artisanat et métiers d'art option Verrerie scientifique et technique",grpM:"B",grpPC:"5"},
  {nom:"Artisanat et métiers d'art - facteur d'orgues",grpM:"B",grpPC:"6"},
  {nom:"Assistance à la gestion des organisations et de leurs activités",grpM:"C",grpPC:""},
  {nom:"Aviation générale",grpM:"B",grpPC:"1"},
  {nom:"Bio-industries de transformation",grpM:"C",grpPC:"5"},
  {nom:"Boucher charcutier traiteur",grpM:"C",grpPC:""},
  {nom:"Boulanger - pâtissier",grpM:"C",grpPC:""},
  {nom:"Carrossier peintre automobile",grpM:"B",grpPC:"1"},
  {nom:"Commercialisation et services en restauration",grpM:"C",grpPC:""},
  {nom:"Conducteur transport routier marchandises",grpM:"B",grpPC:"6"},
  {nom:"Construction des carrosseries",grpM:"B",grpPC:"1"},
  {nom:"Cuisine",grpM:"C",grpPC:""},
  {nom:"Esthétique Cosmétique Parfumerie",grpM:"C",grpPC:"5"},
  {nom:"Étude et définition de produits industriels",grpM:"B",grpPC:"1"},
  {nom:"Etude et réalisation d'agencement",grpM:"B",grpPC:"3"},
  {nom:"Façonnage de produits imprimés, routage",grpM:"B",grpPC:"1"},
  {nom:"Fonderie",grpM:"B",grpPC:"1"},
  {nom:"Gestion des pollutions et protection de l'environnement",grpM:"C",grpPC:"5"},
  {nom:"Hygiène, propreté et stérilisation",grpM:"C",grpPC:"5"},
  {nom:"Installateur en chauffage, climatisation et énergies renouvelables",grpM:"B",grpPC:"1"},
  {nom:"Interventions sur le patrimoine bâti option A - Maçonnerie",grpM:"B",grpPC:"3"},
  {nom:"Interventions sur le patrimoine bâti option B - Charpente",grpM:"B",grpPC:"3"},
  {nom:"Interventions sur le patrimoine bâti option C - Couverture",grpM:"B",grpPC:"3"},
  {nom:"Logistique",grpM:"C",grpPC:""},
  {nom:"Maintenance des matériels option A - Matériels agricoles",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des matériels option B - Matériels de construction et de manutention",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des matériels option C - Matériels d'espaces verts",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des systèmes de production connectés",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des véhicules option A - Voitures particulières",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des véhicules option B - Véhicules de transport routier",grpM:"B",grpPC:"1"},
  {nom:"Maintenance des véhicules option C - Motocycles",grpM:"B",grpPC:"1"},
  {nom:"Maintenance et Efficacité Energétique",grpM:"B",grpPC:"1"},
  {nom:"Maintenance nautique",grpM:"B",grpPC:"1"},
  {nom:"Menuiserie Aluminium-Verre",grpM:"B",grpPC:"3"},
  {nom:"Métiers de l'accueil",grpM:"C",grpPC:""},
  {nom:"Métiers de l'électricité et de ses environnements connectés",grpM:"A",grpPC:"2"},
  {nom:"Métiers de la coiffure",grpM:"C",grpPC:"5"},
  {nom:"Métiers de la mode - vêtements",grpM:"B",grpPC:"6"},
  {nom:"Métiers de la sécurité",grpM:"C",grpPC:""},
  {nom:"Métiers du commerce et de la vente option A",grpM:"C",grpPC:""},
  {nom:"Métiers du commerce et de la vente option B",grpM:"C",grpPC:""},
  {nom:"Métiers du cuir option Chaussures",grpM:"B",grpPC:"6"},
  {nom:"Métiers du cuir option Maroquinerie",grpM:"B",grpPC:"6"},
  {nom:"Métiers du cuir option Sellerie garnissage",grpM:"B",grpPC:"6"},
  {nom:"Métiers du Froid et des Energies Renouvelables",grpM:"B",grpPC:"1"},
  {nom:"Métiers de l'entretien des textiles",grpM:"C",grpPC:"5"},
  {nom:"Métiers et arts de la pierre",grpM:"B",grpPC:"6"},
  {nom:"Microtechniques",grpM:"B",grpPC:"4"},
  {nom:"Modélisation et prototypage 3D",grpM:"B",grpPC:"1"},
  {nom:"Optique lunetterie",grpM:"B",grpPC:"4"},
  {nom:"Organisation de transports de marchandises",grpM:"C",grpPC:""},
  {nom:"Ouvrage du bâtiment : métallerie",grpM:"B",grpPC:"3"},
  {nom:"Perruquier posticheur",grpM:"C",grpPC:"6"},
  {nom:"Photographie",grpM:"B",grpPC:"4"},
  {nom:"Pilote de ligne de production",grpM:"B",grpPC:"6"},
  {nom:"Plastiques et composites",grpM:"B",grpPC:"5"},
  {nom:"Poissonnier écailler traiteur",grpM:"C",grpPC:""},
  {nom:"Procédés de la chimie, de l'eau et des papiers-cartons",grpM:"B",grpPC:"5"},
  {nom:"Réalisation de produits imprimés et plurimédia option A",grpM:"B",grpPC:"4"},
  {nom:"Réalisation de produits imprimés et plurimédia option B",grpM:"B",grpPC:"4"},
  {nom:"Réparation des carrosseries",grpM:"B",grpPC:"1"},
  {nom:"Systèmes numériques option A - Sûreté et sécurité",grpM:"A",grpPC:"2"},
  {nom:"Systèmes numériques option B - Audiovisuels, réseau et équipement domestiques",grpM:"A",grpPC:"2"},
  {nom:"Systèmes numériques option C - Réseaux informatiques et systèmes communicants",grpM:"A",grpPC:"2"},
  {nom:"Technicien constructeur bois",grpM:"B",grpPC:"3"},
  {nom:"Technicien d'études du bâtiment option A - Etudes et économie",grpM:"B",grpPC:"3"},
  {nom:"Technicien d'études du bâtiment option B - Assistant en architecture",grpM:"B",grpPC:"3"},
  {nom:"Technicien de fabrication bois et matériaux associes",grpM:"B",grpPC:"3"},
  {nom:"Technicien de scierie",grpM:"B",grpPC:"6"},
  {nom:"Technicien du bâtiment : organisation et réalisation du gros œuvre",grpM:"B",grpPC:"3"},
  {nom:"Technicien du froid et du conditionnement de l'air",grpM:"B",grpPC:"1"},
  {nom:"Technicien en appareillage orthopédique",grpM:"B",grpPC:"1"},
  {nom:"Technicien en chaudronnerie industrielle",grpM:"B",grpPC:"1"},
  {nom:"Technicien en installation des systèmes énergétiques et climatiques",grpM:"B",grpPC:"1"},
  {nom:"Technicien en prothèse dentaire",grpM:"B",grpPC:"5"},
  {nom:"Technicien en réalisation de produits mécaniques",grpM:"B",grpPC:"1"},
  {nom:"Technicien Gaz",grpM:"B",grpPC:"6"},
  {nom:"Technicien géomètre topographe",grpM:"B",grpPC:"6"},
  {nom:"Technicien menuisier agenceur",grpM:"B",grpPC:"3"},
  {nom:"Technicien modeleur",grpM:"B",grpPC:"1"},
  {nom:"Technicien outilleur",grpM:"B",grpPC:"1"},
  {nom:"Technicien d'usinage",grpM:"B",grpPC:"1"},
  {nom:"Techniques d'interventions sur installations nucléaires",grpM:"B",grpPC:"1"},
  {nom:"Traitement des matériaux",grpM:"C",grpPC:"5"},
  {nom:"Transport fluvial",grpM:"C",grpPC:"1"},
  {nom:"Transports par câbles et remontées mécaniques",grpM:"B",grpPC:"1"},
  {nom:"Travaux publics",grpM:"B",grpPC:"1"},
];

// Dictionnaire dérivé automatiquement — utilisé par grille_items.html
const SPES_GRP = {};
SPECIALITES_BAC_PRO.forEach(s => {
  SPES_GRP[s.nom] = { m: s.grpM, pc: s.grpPC };
});